### PR TITLE
Feature/xunit adaptation

### PR DESCRIPTION
**Pull request by marios-tsiliakos**
Xunit adaptation for Rhino Geometry tests

### CODE REVIEW

**Comment by tmakin** [comment]
@marios-tsiliakos  Many thanks for this. Looks like a useful addition.
 
But please can you remove the MigrationBackup from the PR. I can see you have edited the gitignore to try and block them, but it looks it sneaked in before that.

I'd also prefer to switch to the newer SDK csproj format if adding a new project. Happy to help with that if needs.
https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

**Review by tmakin — APPROVED** [review]
Very tidy, thank you. I can't test it myself as I don't have access to Rhino WIP at the moment, but it all looks fine.

**Comment by marios-tsiliakos** [comment]
Hi @tmakin ,

Wow that was super fast. I just noticed a discrepancy in the naming of the project and namespace which I fixed in my forked copy.

Let me know if it makes any sense of amending this.

Thanks again for sharing the testing solution in the first place.

**Comment by tmakin** [comment]
If it builds fine then leave it - the project is only an example anyway. I should probably go back in and update my original version to SDK format at some point and then I can review namespaces at the same time.

**Comment by marios-tsiliakos** [comment]
Yep, builds fine. 

Sounds good thanks.

**Pull request merged**
